name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix: # 'macos-14' is arm64
       os: ['ubuntu-22.04', 'macos-14', 'windows-2022']
       java: [ 17 ]
       include:
       - os: ubuntu-22.04
         java: 21
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: 'Set up Java ${{ matrix.java }}'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ runner.os }}-${{ matrix.java }}
        path: '**/target/*-reports/TEST*.xml'
